"""remove seed column from users table

Revision ID: 5473d5758aac
Revises: d47b44d93def
Create Date: 2025-11-03 12:32:23.331066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5473d5758aac"
down_revision: Union[str, None] = "d47b44d93def"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "seed")
    # ### end Alembic commands ###
