"""add_departments

Revision ID: 8e3a269adadb
Revises: 5473d5758aac
Create Date: 2025-11-14 18:33:07.922895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8e3a269adadb"
down_revision: Union[str, None] = "5473d5758aac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("department", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.alter_column("users", "city", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "company", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "work_position", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("users", "linkedin_url", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
