"""update user model with optional fields and linkedin

Revision ID: d47b44d93def
Revises: 0994a715f489
Create Date: 2025-11-02 17:15:25.676042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd47b44d93def'
down_revision: Union[str, None] = '0994a715f489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_rating_location_user'), 'rating', type_='unique')
    op.add_column('users', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('work_position', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('users_e_mail_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'name')
    op.drop_column('users', 'e_mail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('e_mail', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_e_mail_key'), 'users', ['e_mail'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'work_position')
    op.drop_column('users', 'company')
    op.drop_column('users', 'city')
    op.drop_column('users', 'email')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.create_unique_constraint(op.f('uq_rating_location_user'), 'rating', ['location_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
